try {
    $1
} catch (${2:Exception}) {
    $0
}